[package]
name = "firezone-client-tunnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
nix = { version =  "0.28.0", features = ["user"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["fs", "io-util", "macros", "net", "rt-multi-thread"] }

[dev-dependencies]
dirs = "5.0.1"
