[package]
name = "snownet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
boringtun = { workspace = true }
getrandom = { version = "0.2.12", features = ["js"] }
instant = "0.1.13"
ip-packet = { workspace = true }
rand = "0.8"
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }
secrecy = { workspace = true }
str0m = { workspace = true }
thiserror = "1"
tracing = { workspace = true }
stun_codec = "0.3.4"
bytecodec = "0.4.15"
bytes = "1.4.0"
once_cell = "1.17.1"
backoff = "0.4.0"
hex = "0.4.0"

[dev-dependencies]
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
# firezone-relay = { workspace = true }

[lints]
workspace = true
