[package]
name = "snownet"
version = "0.1.0"
edition = "2021"

[dependencies]
backoff = "0.4.0"
boringtun = { workspace = true }
bytecodec = "0.4.15"
bytes = "1.4.0"
hex = "0.4.0"
hex-display = "0.3.0"
ip-packet = { workspace = true }
once_cell = "1.17.1"
rand = "0.8"
secrecy = { workspace = true }
str0m = { workspace = true }
stun_codec = "0.3.4"
thiserror = "1"
tracing = { workspace = true }
mutants = "0.0.3"

[dev-dependencies]
firezone-relay = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
