[package]
name = "snownet"
version = "0.1.0"
edition = "2021"

[dependencies]
boringtun = { workspace = true }
ip-packet = { workspace = true }
rand = "0.8"
secrecy = { workspace = true }
str0m = { workspace = true }
thiserror = "1"
tracing = { workspace = true }
stun_codec = "0.3.4"
bytecodec = "0.4.15"
bytes = "1.4.0"
once_cell = "1.17.1"
backoff = "0.4.0"
hex = "0.4.0"
hex-display = "0.3.0"

[dev-dependencies]
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
firezone-relay = { workspace = true }

[lints]
workspace = true
