[package]
name = "snownet"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
backoff = { workspace = true }
boringtun = { workspace = true }
bytecodec = { workspace = true }
bytes = { workspace = true }
firezone-logging = { workspace = true }
hex = { workspace = true }
hex-display = { workspace = true }
ip-packet = { workspace = true }
itertools = { workspace = true }
lockfree-object-pool = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
secrecy = { workspace = true }
sha2 = { workspace = true }
str0m = { workspace = true }
stun_codec = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
