[package]
name = "phoenix-channel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite = { version = "0.20.1", features = ["rustls-tls-native-roots"] }
futures = "0.3.28"
base64 = "0.21.4"
serde = { version = "1.0.188", features = ["derive"] }
tracing = { workspace = true }
rand_core = "0.6.4"
url = "2.4.1"
serde_json = "1.0.107"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["net", "time"] }
