name: "Setup Node"
description: "Sets up the correct Node version and installs pnpm"
inputs:
  node-version:
    description: "Version of nodejs to install"
    required: false
    default: '20'
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
