# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "mix" # See documentation for possible values
    directory: "elixir/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "rust/"
    schedule:
      interval: "weekly"
    groups:
      otel:
        patterns:
          - "opentelemetry"
          - "opentelemetry_api"
          - "opentelemetry-otlp"
          - "tracing-opentelemetry"
          - "tracing-stackdriver"
        update-types:
          - "minor"
  - package-ecosystem: "gradle"
    directory: "rust/connlib/clients/android/connlib"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "kotlin/android"
    schedule:
      interval: "weekly"
  # TODO: Apple package ecosystem
