# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: mix
    directory: elixir/
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: rust/
    schedule:
      interval: daily
    groups:
      otel:
        patterns:
          - opentelemetry
          - opentelemetry_api
          - opentelemetry-otlp
          - tracing-opentelemetry
          - tracing-stackdriver
        update-types:
          - minor
  - package-ecosystem: gradle
    directory: rust/connlib/clients/android/connlib/
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: kotlin/android/
    schedule:
      interval: daily
    ignore:
      # Depends on org.jetbrains.kotlin:kotlin-gradle-plugin version
      - com.google.dagger.hilt.android
      # Depends on JDK version which is bundled with Android Studio (JDK 17)
      - org.jetbrains.kotlin:kotlin-gradle-plugin
  - package-ecosystem: gradle
    directory: kotlin/android/app/
    schedule:
      interval: daily
  - package-ecosystem: swift
    directory: swift/apple/FirezoneKit/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: website/
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: elixir/apps/web/assets/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: terraform/environments/staging/
    schedule:
      interval: daily
