# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: mix
    directory: elixir/
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: rust/
    schedule:
      interval: weekly
    groups:
      netlink:
        patterns:
          - rtnetlink
          - netlink-packet-*
      otel:
        patterns:
          - opentelemetry
          - opentelemetry_api
          - opentelemetry-otlp
          - tracing-opentelemetry
          - tracing-stackdriver
        update-types:
          - minor
  - package-ecosystem: gradle
    directory: rust/connlib/clients/android/connlib/
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: kotlin/android/
    schedule:
      interval: monthly
    groups:
      com.android:
        patters:
          - com.android.*
    ignore:
      # Depends on JDK version which is bundled with Android Studio (JDK 17)
      - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
      - dependency-name: org.jetbrains.kotlin.android
  - package-ecosystem: gradle
    directory: kotlin/android/app/
    schedule:
      interval: monthly
    groups:
      hilt:
        patterns:
          - com.google.dagger.hilt.android
          - com.google.dagger:hilt-android-compiler
  - package-ecosystem: swift
    directory: swift/apple/FirezoneKit/
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: website/
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: elixir/apps/web/assets/
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: terraform/environments/staging/
    schedule:
      interval: monthly
    groups:
      google:
        patterns:
          - hashicorp/google*
  - package-ecosystem: terraform
    directory: terraform/environments/production/
    schedule:
      interval: monthly
    groups:
      google:
        patterns:
          - hashicorp/google*
