# XXX: If this is still too noisy/often, consider distributing on new versions
# only using a version manifest. See elixir/VERSION
distribute/apple:
  - 'swift/apple/*'
  # client-related connlib changes
  - 'rust/connlib/**/*.(rs,lock,toml)'
  # Root-level Rust configuration
  - 'rust/*.(lock,toml)'
distribute/android:
  - 'kotlin/android/*'
  # client-related connlib changes
  - 'rust/connlib/**/*.(rs,lock,toml)'
  # Root-level Rust configuration
  - 'rust/*.(lock,toml)'
