autolabeler:
  - label: chore
    title:
      - '/^chore/i'
  - label: feature
    title:
      - '/^feat/i'
      - '/^feature/i'
  - label: bug
    title:
      - '/^bug/i'
      - '/^fix/i'
  - label: build
    title:
      - '/^build/i'
  - label: ci
    title:
      - '/^ci/i'
  - label: docs
    title:
      - '/^doc/i'
  - label: style
    title:
      - '/^style/i'
  - label: refactor
    title:
      - '/^refactor/i'
  - label: perf
    title:
      - '/^perf/i'
  - label: test
    title:
      - '/^test/i'
  - label: revert
    title:
      - '/^revert/i'
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label:
      - "chore"
      - "dependencies"
  - title: "📝 Documentation"
    label: "docs"
exclude-labels:
  - "skip-changelog"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  $CHANGES
