tag-prefix: "headless-client-"
autolabeler:
  - label: "area/ci"
    title:
      - "/^ci/i"
  - label: "kind/test"
    title:
      - "/^test/i"
  - label: "kind/feature"
    title:
      - "/^feat/i"
  - label: "kind/bug"
    title:
      - "/^fix/i"
      - "/^bug/i"
  - label: "kind/refactor"
    title:
      - "/^refactor/i"
  - label: "kind/chore"
    title:
      - "/^chore/i"
  - label: "kind/docs"
    title:
      - "/^docs/i"
  - label: "kind/security"
    title:
      - "/^security/i"
  - label: "dependencies"
    title:
      - "/^deps/i"
categories:
  - title: "✨ Features"
    labels:
      - "kind/feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "kind/bug"
  - title: "🧰 Maintenance"
    label:
      - "area/ci"
      - "kind/test"
      - "kind/refactor"
      - "kind/chore"
      - "kind/cleanup"
      - "dependencies"
  - title: "📝 Documentation"
    label: "kind/docs"
  - title: "🔐 Security"
    label: "kind/security"
exclude-labels:
  - "skip-changelog"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  Please see our [changelog](https://www.firezone.dev/changelog?utm_source=github-releases)
  for more details.
