name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "kind/feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "kind/bug"
  - title: "🧰 Maintenance"
    label:
      - "kind/refactor"
      - "kind/cleanup"
      - "dependencies"
  - title: "📝 Documentation"
    label: "kind/docs"

  - title: "🔐 Security"
    label: "kind/security"
exclude-labels:
  - "skip-changelog"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  $CHANGES
