[package]
name = "firezone-windows-client"
# mark:automatic-version
version = "1.20231001.0"
description = "Firezone Windows Client"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.4", features = ["derive",  "env"] }
connlib-client-shared = { workspace = true }
directories = "5.0.1"
firezone-cli-utils = { workspace = true }
keyring = "2.0.5"
# Not the newest `open` but this is what Tauri uses internally already
open = "3.2.0"
smbios-lib = "0.9"
secrecy.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.33.0" }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.5.0", features = ["v4"] }

# These dependencies are locked behind `cfg(windows)` because they either can't compile at all on Linux, or they need native dependencies like glib that are difficult to get. Try not to add more here.

[target.'cfg(windows)'.dependencies]
# Tauri works fine on Linux, but it requires a lot of build-time deps like glib and gdk, so I've blocked it out for now.
tauri = { version = "1.5", features = [ "system-tray", "shell-open"] }
tauri-plugin-deep-link = "0.1.2"
wintun = "0.3.2"

[target.'cfg(windows)'.dependencies.windows]
version = "0.52.0"
features = [
  "Win32_Foundation",
  "Win32_System_LibraryLoader",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
