[package]
name = "connlib-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
mock = []
proptest = ["dep:proptest"]

[dependencies]
anyhow = "1.0.82"
base64 = { version = "0.22", default-features = false, features = ["std"] }
boringtun = { workspace = true }
chrono = { workspace = true }
domain = { workspace = true }
futures =  { version = "0.3", default-features = false, features = ["std", "async-await", "executor"] }
futures-util =  { version = "0.3", default-features = false, features = ["std", "async-await", "async-await-macro"] }
ip-packet = { workspace = true }
ip_network = { version = "0.4", default-features = false, features = ["serde"] }
itertools = "0.13"
libc = "0.2"
os_info = { version = "3", default-features = false }
phoenix-channel = { workspace = true }
proptest = { version = "1", optional = true }
rand = { version = "0.8", default-features = false, features = ["std"] }
rand_core = { version = "0.6.4", default-features = false, features = ["std"] }
secrecy = { workspace = true, features = ["serde", "bytes"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
thiserror = { version = "1.0", default-features = false }
tokio = { workspace = true, features = ["fs"] }
tracing = { workspace = true }
url = { version = "2.5.2", default-features = false }
uuid = { version = "1.10", default-features = false, features = ["std", "v4", "serde"] }

[dev-dependencies]
tokio = { version = "1.39", features = ["macros", "rt"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
swift-bridge = { workspace = true }

[lints]
workspace = true
