[package]
name = "connlib-client-android"
# mark:automatic-version
version = "1.0.0"
edition = "2021"

[lib]
name = "connlib"
crate-type = ["lib", "cdylib"]
doc = false

[features]
mock = ["connlib-client-shared/mock"]

[dependencies]
secrecy = { workspace = true }
tracing-android = "0.2"
tracing = { workspace = true, features = ["std", "attributes"] }
tracing-subscriber = { workspace = true }
tracing-appender = "0.2"
connlib-client-shared = { workspace = true }
jni = { version = "0.21.1", features = ["invocation"] }
ip_network = "0.4"
log = "0.4"
serde_json = "1"
thiserror = "1"

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"
