[package]
name = "connlib-android"
# mark:automatic-version
version = "1.20231001.0"
edition = "2021"

[lib]
name = "connlib"
crate-type = ["cdylib"]
doc = false

[features]
mock = ["firezone-client-connlib/mock"]

[dependencies]
secrecy = { workspace = true }
tracing-android = "0.2"
tracing = { workspace = true, features = ["std", "attributes"] }
tracing-subscriber = { workspace = true }
tracing-appender = "0.2"
firezone-client-connlib = { path = "../../libs/client" }
jni = { version = "0.21.1", features = ["invocation"] }
ip_network = "0.4"
log = "0.4"
serde_json = "1"
thiserror = "1"

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2"
