[package]
name = "connlib-android"
version = "0.1.6"
edition = "2021"

[lib]
name = "connlib"
crate-type = ["cdylib"]
doc = false

[features]
mock = ["firezone-client-connlib/mock"]

[dependencies]
android_logger = "0.13"
firezone-client-connlib = { path = "../../libs/client" }
jni = { version = "0.21.1", features = ["invocation"] }
ip_network = "0.4"
log = "0.4"
serde_json = "1"
thiserror = "1"
