[package]
name = "connlib-client-android"
# mark:next-android-version
version = "1.3.8"
edition = "2021"
license = { workspace = true }

[lib]
name = "connlib"
crate-type = ["lib", "cdylib"]
doc = false

[dependencies]
anyhow = { workspace = true }
backoff = { workspace = true }
connlib-client-shared = { workspace = true }
connlib-model = { workspace = true }
firezone-logging = { workspace = true }
firezone-telemetry = { workspace = true }
ip_network = { workspace = true }
jni = { workspace = true, features = ["invocation"] }
libc = { workspace = true }
log = { workspace = true }
phoenix-channel = { workspace = true }
rustls = { workspace = true }
secrecy = { workspace = true }
serde_json = { workspace = true }
socket-factory = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true, features = ["std", "attributes"] }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
tun = { workspace = true }
url = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.3.1"

[lints]
workspace = true
