[package]
name = "connlib-apple"
version = "0.1.6"
edition = "2021"

[features]
mock = ["firezone-client-connlib/mock"]

[build-dependencies]
anyhow = "1.0.72"
diva = "0.1.0"
swift-bridge-build = "0.1.52"
walkdir = "2.3.3"

[dependencies]
libc = "0.2"
swift-bridge = { workspace = true }
firezone-client-connlib = { path = "../../libs/client" }
serde_json = "1"

[lib]
name = "connlib"
crate-type = ["staticlib"]
doc = false
