[package]
name = "connlib-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
mock = []

[dependencies]
boringtun = { workspace = true }
domain = { workspace = true }
ip_network = { version = "0.4", default-features = false, features = ["serde"] }
itertools = "0.13"
phoenix-channel = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
uuid = { version = "1.10", default-features = false, features = ["std", "v4", "serde"] }

[lints]
workspace = true
