[package]
name = "connlib-model"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
boringtun = { workspace = true }
domain = { workspace = true }
ip_network = { workspace = true, features = ["serde"] }
serde = { workspace = true, default-features = false, features = ["derive", "std"] }
uuid = { workspace = true, default-features = false, features = ["std", "v4", "serde"] }

[dev-dependencies]
itertools = { workspace = true }

[lints]
workspace = true
