[package]
name = "connlib-model"
version = "0.1.0"
edition = "2021"

[dependencies]
boringtun = { workspace = true }
domain = { workspace = true }
ip_network = { version = "0.4", default-features = false, features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
uuid = { version = "1.10", default-features = false, features = ["std", "v4", "serde"] }

[dev-dependencies]
itertools = "0.13"

[lints]
workspace = true
