[package]
name = "firezone-connection"
# mark:automatic-version
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
boringtun = { workspace = true }
firezone-relay = { workspace = true }
pnet_packet = { version = "0.34" }
rand = "0.8"
secrecy = { workspace = true }
str0m = { workspace = true }
thiserror = "1"
tracing = "0.1"
stun_codec = "0.3.4"
bytecodec = "0.4.15"
