blank_issues_enabled: true
contact_links:
  - name: "Community Support - Discussion Forums"
    url: "https://discourse.firez.one"
    about: "Ask questions, get help from other Firezone users, and suggest features."
  - name: "Community Support - Slack"
    url: "https://join.slack.com/t/firezone-users/shared_invite/zt-111043zus-j1lP_jP5ohv52FhAayzT6w"
    about: "Join discussions, meet other users, and get updates from the Firezone team."
