blank_issues_enabled: true
contact_links:
  - name: "Community Support - Discussion Forums"
    url: "https://discourse.firez.one"
    about: "Ask questions, get help from other Firezone users, and suggest features."
  - name: "Community Support - Discord"
    url: "https://discord.gg/DY8gxpSgep"
    about: "Join discussions, meet other users, and get updates from the Firezone team."
