[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firezone-gateway-connlib = { path = "../libs/gateway" }
headless-utils = { path = "../headless-utils" }
anyhow = { version = "1.0" }
tracing = { workspace = true }
clap = { version = "4.3", features = ["derive",  "env"] }
