[package]
name = "ip-packet"
version = "0.1.0"
edition = "2021"
authors = ["Firezone, Inc."]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet_packet = { version = "0.34" }
hickory-proto = { workspace = true }

[lints]
workspace = true
