[package]
name = "connlib-gateway-shared"
# mark:automatic-version
version = "1.20231001.0"
edition = "2021"

[dependencies]
secrecy = { workspace = true }
connlib-shared = { workspace = true }
async-trait = { version = "0.1", default-features = false }
firezone-tunnel = { workspace = true }
tokio = { version = "1.32", default-features = false, features = ["sync"] }
tracing = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
boringtun = { workspace = true }
chrono = { workspace = true }
backoff = { workspace = true }
webrtc = "0.8"
url = { version = "2.4.1", default-features = false }
rand = { version = "0.8", default-features = false, features = ["std"] }
tokio-tungstenite = { version = "0.20", default-features = false, features = ["connect", "handshake", "rustls-tls-webpki-roots"] }

[dev-dependencies]
serde_json = { version = "1.0", default-features = false, features = ["std"] }
