[package]
name = "headless-utils"
# mark:automatic-version
version = "1.20231001.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
connlib-client-shared = { workspace = true }
ip_network = "0.4"
url = { version = "2.3.1", default-features = false }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { version = "4.3", features = ["derive",  "env"] }
ctrlc  = "3.4"
