[package]
name = "firezone-client-shared"
# mark:automatic-version
version = "1.20231001.0"
edition = "2021"

[features]
mock = ["libs-common/mock"]

[dependencies]
tokio = { version = "1.32", default-features = false, features = ["sync", "rt"] }
tokio-util = "0.7.9"
secrecy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-appender = { version = "0.2.2" }
tracing-stackdriver = { version = "0.8.0" }
async-trait = { version = "0.1", default-features = false }
libs-common = { workspace = true }
firezone-tunnel = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
boringtun = { workspace = true }
backoff = { workspace = true }
webrtc = "0.8"
url = { version = "2.4.1", features = ["serde"] }
time = { version = "0.3.29", features = ["formatting"] }
reqwest = { version = "0.11.20", default-features = false, features = ["stream", "rustls-tls"] }
rand = { version = "0.8", default-features = false, features = ["std"] }
tokio-tungstenite = { version = "0.20", default-features = false, features = ["connect", "handshake", "rustls-tls-webpki-roots"] }

[target.'cfg(target_os = "android")'.dependencies]
tracing = { workspace = true, features = ["std", "attributes"] }
tracing-android = "0.2"

[dev-dependencies]
serde_json = { version = "1.0", features = ["std"] }
chrono = { workspace = true }
