[package]
name = "connlib-client-shared"
version = "0.1.0"
edition = "2021"

[features]
mock = ["connlib-model/mock"]

[dependencies]
anyhow = "1.0.82"
backoff = { workspace = true }
bimap = "0.6"
connlib-model = { workspace = true }
firezone-logging = { workspace = true }
firezone-tunnel = { workspace = true }
ip_network = { version = "0.4", default-features = false }
phoenix-channel = { workspace = true }
secrecy = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
socket-factory = { workspace = true }
thiserror = "1.0.63"
time = { version = "0.3.36", features = ["formatting"] }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true, features = ["std", "attributes"] }
tun = { workspace = true }
url = { version = "2.4.1", features = ["serde"] }

[dev-dependencies]
chrono = { workspace = true }
serde_json = { version = "1.0", features = ["std"] }

[lints]
workspace = true
