[package]
name = "connlib-client-shared"
version = "0.1.0"
edition = "2021"

[features]
mock = ["connlib-shared/mock"]

[dependencies]
anyhow = "1.0.82"
backoff = { workspace = true }
bimap = "0.6"
connlib-shared = { workspace = true }
firezone-tunnel = { workspace = true }
ip_network = { version = "0.4", default-features = false }
phoenix-channel = { workspace = true }
secrecy = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
socket-factory = { workspace = true }
thiserror = "1.0.63"
tokio = { workspace = true, features = ["sync"] }
tokio-tungstenite = { version = "0.21", default-features = false, features = ["connect", "handshake", "rustls-tls-webpki-roots"] }
tracing = { workspace = true }
tun = { workspace = true }
url = { version = "2.5.2", features = ["serde"] }

[target.'cfg(target_os = "android")'.dependencies]
tracing = { workspace = true, features = ["std", "attributes"] }

[dev-dependencies]
chrono = { workspace = true }
serde_json = { version = "1.0", features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
