[package]
name = "firezone-bin-shared"
version = "0.1.0"
edition = "2021"
description = "Firezone-specific modules shared between binaries."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5", features = ["derive",  "env"] }
connlib-shared = { workspace = true }
futures = "0.3"
ip-packet = { workspace = true }
ip_network = { version = "0.4", default-features = false, features = ["serde"] }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }
tracing-log = "0.2"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tun = { workspace = true }
url = { version = "2.5.2", default-features = false }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
netlink-packet-core = { version = "0.7", default-features = false }
netlink-packet-route = { version = "0.19", default-features = false }
rtnetlink = { workspace = true }
zbus = "4.4"

[target.'cfg(target_os = "windows")'.dependencies]
wintun = "0.4.0"
uuid = { version = "1.10.0", features = ["v4"] }

[target.'cfg(windows)'.dependencies.windows]
version = "0.57.0"
features = [
  "Win32_Foundation",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
]

[lints]
workspace = true

[[bench]]
name = "tunnel"
harness = false
