[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread", "net"] }
nom = "7.1.3"
anyhow = "1.0.71"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = "0.3"
bytes = "1.4.0"

[dev-dependencies]
hex-literal = "0.4.1"
hex = "0.4.3"
