[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bytecodec = "0.4.15"
futures = "0.3.28"
hex = "0.4.3"
hex-literal = "0.4.1"
rand = "0.8.5"
stun_codec = "0.3.1"
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread", "net", "time"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
env_logger = "0.10.0"
bytes = "1.4.0"

[dev-dependencies]
webrtc = "0.7.2"
redis = { version = "0.23.0", default-features = false, features = ["tokio-comp"] }
