[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive", "env"] }
bytecodec = "0.4.15"
futures = "0.3.28"
hex = "0.4.3"
hex-literal = "0.4.1"
rand = "0.8.5"
stun_codec = "0.3.3"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "net", "time"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "fmt"] }
tracing-stackdriver = { version = "0.7.2", features = ["opentelemetry"] }
tracing-opentelemetry = "0.19.0"
opentelemetry = { version = "0.19.0", features = ["rt-tokio", "metrics"] }
opentelemetry_api = "0.19.0"
opentelemetry-otlp = { version = "0.12.0", features = ["metrics"]}
env_logger = "0.10.0"
tracing-core = "0.1.31"
bytes = "1.4.0"
sha2 = "0.10.6"
base64 = "0.21.4"
once_cell = "1.17.1"
proptest = { version = "1.2.0", optional = true }
test-strategy = "0.3.1"
derive_more = { version = "0.99.17", features = ["from"] }
uuid = { version = "1.4.1", features = ["v4"] }
phoenix-channel = { path = "../phoenix-channel" }
url = "2.4.1"
serde = { version = "1.0.188", features = ["derive"] }
trackable = "1.3.0"
socket2 = "0.5.4"
axum = { version = "0.6.20", default-features = false, features = ["http1", "tokio"] }

[dev-dependencies]
webrtc = { version = "0.8" }
redis = { version = "0.23.3", default-features = false, features = ["tokio-comp"] }
difference = "2.0.0"

[[test]]
name = "regression"
required-features = ["proptest"]
