[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.2", features = ["derive", "env"] }
bytecodec = "0.4.15"
futures = "0.3.28"
hex = "0.4.3"
hex-literal = "0.4.1"
rand = "0.8.5"
stun_codec = "0.3.1"
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread", "net", "time"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-stackdriver = "0.7.2"
env_logger = "0.10.0"
bytes = "1.4.0"
sha2 = "0.10.6"
base64 = "0.21.0"
once_cell = "1.17.1"
proptest = { version = "1.2.0", optional = true }
test-strategy = "0.3.0"
derive_more = { version = "0.99.17", features = ["from"] }
uuid = { version = "1.4.1", features = ["v4"] }
phoenix-channel = { path = "../phoenix-channel" }
url = "2.4.0"
serde = { version = "1.0.171", features = ["derive"] }
prometheus-client = "0.21.1"
axum = { version = "0.6.18", default-features = false, features = ["http1", "tokio"] }

[dev-dependencies]
webrtc = { version = "0.8" }
redis = { version = "0.23.0", default-features = false, features = ["tokio-comp"] }
difference = "2.0.0"

[[test]]
name = "regression"
required-features = ["proptest"]
