[workspace]
members = [
  "connlib/clients/android",
  "connlib/clients/apple",
  "connlib/clients/shared",
  "connlib/shared",
  "connlib/tunnel",
  "connlib/connection",
  "gateway",
  "linux-client",
  "firezone-cli-utils",
  "connection-tests",
  "phoenix-channel",
  "relay",
  "windows-client/src-tauri",
]

resolver = "2"

[workspace.dependencies]
boringtun = { version = "0.6", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
swift-bridge = "0.1.52"
backoff = { version = "0.4", features = ["tokio"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.17", features = ["parking_lot"] }
secrecy = "0.8"
hickory-resolver = { version = "0.24", features = ["tokio-runtime"] }
webrtc = "0.9"
str0m = "0.4"
futures-bounded = "0.2.1"
domain = { version = "0.9", features = ["serde"] }
dns-lookup = "2.0"

connlib-client-android = { path = "connlib/clients/android"}
connlib-client-apple = { path = "connlib/clients/apple"}
connlib-client-shared = { path = "connlib/clients/shared"}
firezone-gateway = { path = "gateway"}
firezone-linux-client = { path = "linux-client"}
firezone-windows-client = { path = "windows-client/src-tauri"}
firezone-cli-utils = { path = "firezone-cli-utils"}
firezone-connection = { path = "connlib/connection"}
firezone-relay = { path = "relay"}
connlib-shared = { path = "connlib/shared"}
firezone-tunnel = { path = "connlib/tunnel"}
phoenix-channel = { path = "phoenix-channel"}

[patch.crates-io]
boringtun = { git = "https://github.com/cloudflare/boringtun", branch = "master" } # Contains unreleased patches we need (bump of x25519-dalek)
webrtc = { git = "https://github.com/firezone/webrtc", branch = "expose-new-endpoint" }
str0m = { git = "https://github.com/thomaseizinger/str0m", branch = "main" }

[profile.release]
strip = true

# Override build settings just for the Windows client, so we get a pdb
[profile.release.package.firezone-windows-client]
# Generate debug symbols for the crash handler to use, even if the exe itself is optimized
debug = "full"
# Split out debug info from the exe. This is already default on Windows.
# https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo
split-debuginfo = "packed"
