[workspace]
members = [
  "relay",
  "phoenix-channel",
  "connlib/clients/android",
  "connlib/clients/apple",
  "connlib/clients/headless",
  "connlib/libs/tunnel",
  "connlib/libs/client",
  "connlib/libs/gateway",
  "connlib/libs/common",
  "connlib/gateway",
  "connlib/macros",
]

[workspace.dependencies]
boringtun = { git = "https://github.com/cloudflare/boringtun", rev = "878385f", default-features = false }
swift-bridge = { git = "https://github.com/chinedufn/swift-bridge.git", rev = "4fbd30f" }
