[workspace]
members = [
  "connlib/clients/android",
  "connlib/clients/apple",
  "connlib/clients/shared",
  "connlib/shared",
  "connlib/tunnel",
  "connlib/snownet",
  "gateway",
  "linux-client",
  "firezone-cli-utils",
  "snownet-tests",
  "phoenix-channel",
  "relay",
  "gui-client/src-tauri",
  "http-health-check",
]

resolver = "2"

[workspace.dependencies]
boringtun = { version = "0.6", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
swift-bridge = "0.1.52"
backoff = { version = "0.4", features = ["tokio"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.17", features = ["parking_lot"] }
secrecy = "0.8"
hickory-resolver = { git = "https://github.com/hickory-dns/hickory-dns", rev="a3669bd80f3f7b97f0c301c15f1cba6368d97b63", features = ["tokio-runtime"] }
str0m = { version = "0.4", default-features = false }
futures-bounded = "0.2.1"
domain = { version = "0.9", features = ["serde"] }
dns-lookup = "2.0"
tokio-tungstenite = "0.21"
rtnetlink = { version = "0.14.1", default-features = false, features = ["tokio_socket"] }

connlib-client-android = { path = "connlib/clients/android"}
connlib-client-apple = { path = "connlib/clients/apple"}
connlib-client-shared = { path = "connlib/clients/shared"}
firezone-gateway = { path = "gateway"}
firezone-linux-client = { path = "linux-client"}
firezone-gui-client = { path = "gui-client/src-tauri"}
firezone-cli-utils = { path = "firezone-cli-utils"}
snownet = { path = "connlib/snownet"}
firezone-relay = { path = "relay"}
connlib-shared = { path = "connlib/shared"}
firezone-tunnel = { path = "connlib/tunnel"}
phoenix-channel = { path = "phoenix-channel"}
http-health-check = { path = "http-health-check"}

[patch.crates-io]
boringtun = { git = "https://github.com/cloudflare/boringtun", branch = "master" }
str0m = { git = "https://github.com/firezone/str0m", branch = "main" }
tracing-stackdriver = { git = "https://github.com/thomaseizinger/tracing-stackdriver", branch = "deps/bump-otel-0.22" }

[profile.release]
strip = true

# Override build settings just for the GUI client, so we get a pdb/dwp
[profile.dev.package.firezone-gui-client]
debug = "full"
split-debuginfo = "packed"

[profile.release.package.firezone-gui-client]
# Generate debug symbols for the crash handler to use, even if the exe itself is optimized
debug = "full"
# Split out debug info from the exe. This is already default on Windows.
# https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo
split-debuginfo = "packed"
# Since we have separate symbol files, strip the debuginfo from the exe itself
strip = "symbols"
