[workspace]
members = [
  "connlib/clients/android",
  "connlib/clients/apple",
  "connlib/clients/shared",
  "connlib/shared",
  "connlib/tunnel",
  "gateway",
  "hello-world",
  "linux-client",
  "firezone-cli-utils",
  "phoenix-channel",
  "relay",
  "windows-client/src-tauri",
]

resolver = "2"

[workspace.dependencies]
boringtun = { version = "0.6", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "oldtime", "serde"] }
swift-bridge = "0.1.52"
backoff = { version = "0.4", features = ["tokio"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.17", features = ["parking_lot"] }
secrecy = "0.8"
hickory-resolver = { version = "0.24", features = ["tokio-runtime"] }
webrtc = "0.9"
futures-bounded = "0.2.1"
domain = { version = "0.9", features = ["serde"] }

connlib-client-android = { path = "connlib/clients/android"}
connlib-client-apple = { path = "connlib/clients/apple"}
connlib-client-shared = { path = "connlib/clients/shared"}
firezone-gateway = { path = "gateway"}
firezone-linux-client = { path = "linux-client"}
firezone-windows-client = { path = "windows-client/src-tauri"}
firezone-cli-utils = { path = "firezone-cli-utils"}
connlib-shared = { path = "connlib/shared"}
firezone-tunnel = { path = "connlib/tunnel"}
phoenix-channel = { path = "phoenix-channel"}

[patch.crates-io]
boringtun = { git = "https://github.com/cloudflare/boringtun", branch = "master" } # Contains unreleased patches we need (bump of x25519-dalek)
webrtc = { git = "https://github.com/firezone/webrtc", branch = "expose-new-endpoint" }

# Cargo does not let me set LTO to off for just the Windows client
[profile.unopt]
inherits = "dev"
lto = "off"

[profile.release]
strip = true
