[toolchain]
channel = "1.71.0"
components = ["rustfmt", "clippy"]
targets = [
  "x86_64-unknown-linux-musl",
  "x86_64-linux-android",
  "arm-linux-androideabi",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "i686-linux-android",
  "aarch64-apple-ios-sim",
  "aarch64-apple-ios",
  "aarch64-apple-darwin",
  "x86_64-apple-ios",
  "x86_64-apple-darwin",
]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
