[toolchain]
channel = "1.73.0"
components = ["rustfmt", "clippy"]
targets = [
  "x86_64-unknown-linux-musl",
  "x86_64-linux-android",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "aarch64-apple-ios",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
]
