[package]
name = "firezone-gui-client-common"
# mark:next-gui-version
version = "1.3.1"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
firezone-headless-client = { path = "../../headless-client" }
hex = "0.4.3"
rand = "0.8.5"
secrecy = { workspace = true }
subtle = "2.5.0"
thiserror = { version = "1.0", default-features = false }
tracing = { workspace = true }
url = { version = "2.5.2" }

[dependencies.keyring]
version = "3.2.1"
features = [
    "crypto-rust", # Don't rely on OpenSSL
    "sync-secret-service", # Can't use Tokio because of <https://github.com/hwchen/keyring-rs/issues/132>
    "windows-native", # Yes, really, we must actually explicitly ask for every platform. Otherwise it defaults to an in-memory mock store. Really. That's really how `keyring` 3.x is designed.
]

[lints]
workspace = true
