[package]
name = "socket-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1", optional = true }
hickory-proto = { workspace = true, optional = true }
quinn-udp = { git = "https://github.com/quinn-rs/quinn", branch = "main" }
socket2 = { workspace = true }
tokio = { version = "1.38", features = ["net"] }
tracing = "0.1"

[features]
hickory = ["dep:hickory-proto", "dep:async-trait"]
