[package]
name = "socket-factory"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
firezone-logging = { workspace = true }
quinn-udp = "0.5.2"
socket2 = { workspace = true }
tokio = { version = "1.41", features = ["net"] }
tracing = "0.1"
