[package]
name = "socket-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13"
quinn-udp = "0.5.2"
socket2 = { workspace = true }
tokio = { version = "1.39", features = ["net"] }
tracing = "0.1"
