[package]
name = "socket-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn-udp = { git = "https://github.com/quinn-rs/quinn", branch = "main" }
socket2 = { workspace = true }
tokio = { version = "1.39", features = ["net"] }
tracing = "0.1"
