[package]
name = "firezone-windows-client"
# mark:automatic-version
version = "1.20231001.0"
edition = "2021"

[dependencies.windows]
version = "0.52.0"
features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging",
]
