[package]
name = "firezone-linux-client"
# mark:automatic-version
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secrecy = { workspace = true }
connlib-client-shared = { workspace = true }
firezone-cli-utils = { workspace = true }
anyhow = { version = "1.0" }
tracing = { workspace = true }
clap = { version = "4.4", features = ["derive",  "env"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
humantime = "2.1"
