[package]
name = "iced-client"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image", "multi-window"], default-features = false }

[lints]
workspace = true
