[package]
name = "headless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firezone-client-connlib = { path = "../../libs/client" }
headless-utils = { path = "../../headless-utils" }
anyhow = { version = "1.0" }
tracing = { workspace = true }
clap = { version = "4.4", features = ["derive",  "env"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
