[package]
name = "headless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmidecode = "0.7"
firezone-client-connlib = { path = "../../libs/client" }
ip_network = "0.4"
url = { version = "2.3.1", default-features = false }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
anyhow = { version = "1.0" }
clap = { version = "4.3", features = ["derive",  "env"] }
ctrlc  = "3.4"
tracing-flame = { path = "../../../../../tracing/tracing-flame" }