# From https://tauri.app/v1/guides/getting-started/prerequisites
name: "Setup Tauri"
description: "Sets up the dependencies for building and testing Tauri apps"
inputs:
  target_os:
    description: "`windows` or `linux` like in Rust"
    required: true
runs:
  using: "composite"
  steps:
    - name: Apt-get install Tauri build deps
      if: ${{ inputs.target_os == 'linux' }}
      run: sudo apt-get install libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      shell: bash
    - name: Download WebView2 bootstrapper
      if: ${{ inputs.target_os == 'windows' }}
      # This is the "Evergreen" bootstrapper from Microsoft
      # <https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download>
      # Unfortunately, this makes the test non-deterministic.
      # Controlling the version would be difficult.
      run: Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/p/?LinkId=2124703 -OutFile WebView2Installer.exe
      shell: pwsh
    - name: Install WebView2
      if: ${{ inputs.target_os == 'windows' }}
      # This downloads about 200 MB and takes about 5 minutes on my VM
      # So we could fault in WebView2 from the client exe without the MSI if we needed.
      # Currently the MSI does this and it's a little janky.
      run: Start-Process WebView2Installer.exe -ArgumentList "/install" -Wait
      shell: pwsh
