[package]
name = "firezone-headless-client"
# mark:automatic-version
version = "1.0.0"
edition = "2021"
authors = ["Firezone, Inc."]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.5", features = ["derive",  "env"] }
humantime = "2.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
# This actually relies on many other features in Tokio, so this will probably
# fail to build outside the workspace. <https://github.com/firezone/firezone/pull/4328#discussion_r1540342142>
tokio = { version = "1.36.0", features = ["macros", "signal"] }
url = { version = "2.3.1", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
connlib-client-shared = { workspace = true }
connlib-shared = { workspace = true }
dirs = "5.0.1"
firezone-cli-utils = { workspace = true }
nix = { version =  "0.28.0", features = ["user"] }
resolv-conf = "0.7.0"
secrecy = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
