[package]
name = "firezone-gateway"
# mark:next-gateway-version
version = "1.3.2"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
async-trait = { version = "0.1", default-features = false }
backoff = { workspace = true }
boringtun = { workspace = true }
chrono = { workspace = true }
clap = "4.5.13"
connlib-model = { workspace = true }
dns-lookup = { workspace = true }
domain = { workspace = true }
either = "1"
firezone-bin-shared = { workspace = true }
firezone-logging = { workspace = true }
firezone-tunnel = { workspace = true }
futures = "0.3.29"
futures-bounded = { workspace = true }
ip-packet = { workspace = true }
ip_network = { version = "0.4", default-features = false }
libc = { version = "0.2", default-features = false, features = ["std", "const-extern-fn", "extra_traits"] }
phoenix-channel = { workspace = true }
rustls = { workspace = true }
secrecy = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
snownet = { workspace = true }
socket-factory = { workspace = true }
static_assertions = "1.1.0"
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread", "fs", "signal"] }
tracing = { workspace = true }
tracing-subscriber = "0.3.17"
url = { version = "2.5.2", default-features = false }
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
serde_json = { version = "1.0", default-features = false, features = ["std"] }

[lints]
workspace = true
