[package]
name = "firezone-gateway"
# mark:automatic-version
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = { version = "0.1", default-features = false }
backoff = { workspace = true }
boringtun = { workspace = true }
chrono = { workspace = true }
clap = "4.4.13"
connlib-shared = { workspace = true }
firezone-tunnel = { workspace = true }
futures = "0.3.29"
futures-bounded = { workspace = true }
firezone-cli-utils = { workspace = true }
phoenix-channel = { workspace = true }
secrecy = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
tokio = { version = "1.33", default-features = false, features = ["sync", "macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.21", default-features = false, features = ["connect", "handshake", "rustls-tls-webpki-roots"] }
tracing = { workspace = true }
tracing-subscriber = "0.3.17"
url = { version = "2.4.1", default-features = false }
webrtc = { workspace = true }
domain = { workspace = true }
uuid = { version = "1.6.1", features = ["v4"] }

[dev-dependencies]
serde_json = { version = "1.0", default-features = false, features = ["std"] }
