[package]
name = "gtk-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
glib = "0.18.5"
gtk = "0.18.1"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "time"] }
tray-icon = "0.19.0"

[workspace]
