name: Kotlin
on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./kotlin/android

permissions:
  contents: "read"
  id-token: "write"

jobs:
  static-analysis:
    # Android SDK tools hardware accel is available only on Linux runners
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-android
      - name: Run linter
        run: ./gradlew spotlessCheck

  build_release:
    permissions:
      contents: write # for uploading artifacts to the release
      id-token: write
    name: build-release-${{ matrix.package-type }}
    # Android SDK tools hardware accel is available only on Linux runners
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - package-type: aab
            build-command: "./gradlew bundleRelease"
            output-path: app/build/outputs/bundle/release/app-release.aab
          - package-type: apk
            build-command: "./gradlew assembleRelease"
            output-path: app/build/outputs/apk/release/app-release.apk
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-tags: true # Otherwise we cannot embed the correct version into the build.
      - uses: ./.github/actions/setup-android
      - name: Build the release package
        env:
          KEYSTORE_BASE64: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_KEY_PASSWORD }}
        run: |
          KEYSTORE_PATH="$(pwd)/app/keystore.jks"
          echo -n "$KEYSTORE_BASE64" | base64 --decode > "$KEYSTORE_PATH"
          ${{ matrix.build-command }}
          rm "$KEYSTORE_PATH"
      - name: Run Unit Test
        run: |
          ./gradlew testReleaseUnitTest
      - name: Upload package artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: Android ${{ matrix.package-type }}
          path: |
            ./kotlin/android/${{ matrix.output-path }}
      - name: Upload package to release
        if: ${{ matrix.package-type == 'apk' && github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # mark:next-android-version
          RELEASE_NAME: android-client-1.4.1
        run: |
          export ARTIFACT_PATH="$RUNNER_TEMP/firezone-${RELEASE_NAME}.${{ matrix.package-type }}"
          cp "${{ matrix.output-path }}" "$ARTIFACT_PATH"
          ../../scripts/upload/github-release.sh
      - name: Distribute release to Firebase App Distribution
        if: ${{ matrix.package-type == 'aab' && github.event_name == 'workflow_dispatch' }}
        env:
          FIREBASE_APP_DISTRIBUTION_CREDENTIALS: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}
          FIREBASE_CREDENTIALS_PATH: firebase-credentials.json
          FIREBASE_APP_TESTERS: ${{ vars.FIREBASE_APP_TESTERS }}
        run: |
          echo -n "$FIREBASE_APP_DISTRIBUTION_CREDENTIALS" > $FIREBASE_CREDENTIALS_PATH
          ./gradlew appDistributionUploadRelease uploadCrashlyticsSymbolFileRelease

  update-release-draft:
    name: update-release-draft
    needs: build_release
    runs-on: ubuntu-22.04
    env:
      # mark:next-android-version
      RELEASE_NAME: android-client-1.4.1
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        if: "${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'main' }}"
        id: update-release-draft
        with:
          config-name: release-drafter-android-client.yml
          tag: ${{ env.RELEASE_NAME }}
          version: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_debug:
    # Android SDK tools hardware accel is available only on Linux runners
    runs-on: ubuntu-22.04
    name: build-debug
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-android
      - name: Build debug APK
        run: |
          ./gradlew assembleDebug
      - name: Upload debug APK
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: Android debug APK
          path: |
            ./kotlin/android/app/build/outputs/apk/*
