name: Kotlin
on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./kotlin/android

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  static-analysis:
    # Android SDK tools hardware accel is available only on Linux runners
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: ./kotlin/android
      - run: touch local.properties
      - name: Run linter
        run: ./gradlew spotlessCheck

  build:
    # Android SDK tools hardware accel is available only on Linux runners
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          targets: armv7-linux-androideabi aarch64-linux-android x86_64-linux-android i686-linux-android
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: ./kotlin/android
      - run: touch local.properties
      - name: Bundle and sign release
        env:
          # mark:next-android-version
          FIREZONE_PACKAGE_VERSION: 1.0.4
          FIREZONE_PACKAGE_NAME: android
          KEYSTORE_BASE64: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_KEY_PASSWORD }}
        run: |
          KEYSTORE_PATH=$(pwd)/app/keystore.jks
          echo -n "$KEYSTORE_BASE64" | base64 --decode > $KEYSTORE_PATH
          ./gradlew bundleRelease
      - name: Run Unit Test
        run: |
          ./gradlew testReleaseUnitTest
      - name: Upload app bundle
        uses: actions/upload-artifact@v4
        with:
          name: Android app bundle
          path: |
            ./kotlin/android/app/build/outputs/bundle/*
      - name: Upload release
        if: ${{ github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/main' && contains(github.event.head_commit.modified, 'elixir/VERSION')) }}
        env:
          FIREBASE_APP_DISTRIBUTION_CREDENTIALS: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}
          FIREBASE_CREDENTIALS_PATH: firebase-credentials.json
          FIREBASE_APP_TESTERS: ${{ vars.FIREBASE_APP_TESTERS }}
        run: |
          echo -n "$FIREBASE_APP_DISTRIBUTION_CREDENTIALS" > $FIREBASE_CREDENTIALS_PATH
          ./gradlew --info appDistributionUploadRelease uploadCrashlyticsSymbolFileRelease

  ui-test:
    # FIXME
    # Currently flaky, see https://github.com/firezone/firezone/pull/4178#issuecomment-2094815889
    if: false
    name: ui-test-api-${{ matrix.api-level }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: These currently time out and/or fail intermittently.
          # https://github.com/ReactiveCircus/android-emulator-runner/issues/385
          - api-level: 26
          - api-level: 29
    # Android SDK tools hardware accel is available only on Linux runners
    runs-on: ubuntu-22.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          targets: i686-linux-android
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      # Test on x86_64 only -- prevents compiling for other targets.
      # See https://github.com/mozilla/rust-android-gradle?tab=readme-ov-file#specifying-local-targets
      - run: echo 'rust.targets=x86' > local.properties
      # See https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
          working-directory: ./kotlin/android
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew --stacktrace connectedCheck
          working-directory: ./kotlin/android
