name: Rust
on:
  workflow_call:

defaults:
  run:
    working-directory: ./rust

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  static-analysis:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          # We only need to run static analysis checks per OS family
          - ubuntu-22.04
          - macos-13
          - windows-2022
        # TODO: https://github.com/rust-lang/cargo/issues/5220
        include:
          - runs-on: ubuntu-22.04
            packages: # Intentionally blank as a package catch-all linter
          - runs-on: macos-13
            packages: -p connlib-client-apple
          - runs-on: windows-2022
            packages: -p connlib-client-shared -p firezone-windows-client
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - run: cargo fmt -- --check
      - run: |
          cargo doc --all-features --no-deps --document-private-items ${{ matrix.packages }}
        env:
          RUSTDOCFLAGS: "-D warnings"
      - run: |
          cargo clippy --all-targets --all-features ${{ matrix.packages }} -- -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO: https://github.com/rust-lang/cargo/issues/5220
        include:
          - runs-on: ubuntu-20.04
            packages: -p firezone-linux-client -p firezone-gateway -p connlib-client-android
          - runs-on: ubuntu-22.04
            packages: -p firezone-linux-client -p firezone-gateway -p connlib-client-android
          - runs-on: macos-12
            packages: -p connlib-client-apple
          - runs-on: macos-13
            packages: -p connlib-client-apple
          - runs-on: windows-2019
            packages: -p firezone-windows-client -p connlib-client-shared
          - runs-on: windows-2022
            packages: -p firezone-windows-client -p connlib-client-shared
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - run: cargo test --all-features ${{ matrix.packages }}

  # This should be identical to `build-push-windows-release-artifacts` in `cd.yml` except for the permissions, needs, and uploading step
  # TODO: Get rid of "temp" and figure out what to do with this
  build-tauri:
    runs-on: windows-2019
    defaults:
      run:
        working-directory: ./rust
    strategy:
      fail-fast: false
      matrix:
        arch:
          - target: aarch64-pc-windows-msvc
            shortname: arm64
          - target: x86_64-pc-windows-msvc
            shortname: x64
        name:
          - package: firezone-windows-client
            artifact: windows-client
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          targets: ${{ matrix.arch.target }}
      - name: Build release binaries
        run: |
          # Install Tauri build tool
          npm install -g @tauri-apps/cli

          tauri build -- -p ${{ matrix.name.package }} --target ${{ matrix.arch.target }}

          # Rename the portable exe to include architecture.
          # CI doesn't need this, but CD does, so do the same in both
          cp "target/${{ matrix.arch.target }}/release/Firezone Windows Client.exe" "firezone-windows-client-${{ matrix.arch.shortname }}.exe"
      # I think BINARY_DEST_PATH maybe isn't available for these
      - name: Upload Windows exe
        uses: actions/upload-artifact@v3
        with:
          name: windows-client-${{ matrix.arch.shortname }}
          path: ${{ github.workspace }}/rust/firezone-windows-client-${{ matrix.arch.shortname }}.exe
      - name: Upload Windows installer
        uses: actions/upload-artifact@v3
        with:
          name: windows-client-${{ matrix.arch.shortname }}-msi
          path: ${{ github.workspace }}/rust/target/${{ matrix.arch.target }}/release/bundle/msi

  smoke-test-relay:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./rust/relay
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - run: ./run_smoke_test.sh
