name: Continuous Integration
on:
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  elixir:
    uses: ./.github/workflows/elixir.yml
  rust:
    uses: ./.github/workflows/rust.yml
  kotlin:
    uses: ./.github/workflows/kotlin.yml
  swift:
    uses: ./.github/workflows/swift.yml
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit

  # We could build these in GCP with Cloud Build, but for now it's
  # less overhead to keep things in GH actions. See work on building these
  # in GCP with Cloud Build: https://github.com/firezone/firezone/pull/2234
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image_name: api
            cache_scope: elixir
          - image_name: web
            cache_scope: elixir
          - image_name: gateway
            cache_scope: rust
          - image_name: relay
            cache_scope: rust
    needs:
      - rust
      - elixir
      - static-analysis
    permissions:
      contents: read
      id-token: write
    env:
      # mark:automatic-version
      VERSION: "1.20231001.0"
      APPLICATION_NAME: ${{ matrix.image_name }}
      REGISTRY: us-east1-docker.pkg.dev
      GCLOUD_PROJECT: firezone-staging
      GOOGLE_CLOUD_PROJECT: firezone-staging
      CLOUDSDK_PROJECT: firezone-staging
      CLOUDSDK_CORE_PROJECT: firezone-staging
      GCP_PROJECT: firezone-staging
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
          export_environment_variables: false
      - name: Change current gcloud account
        run: gcloud --quiet config set project ${GCLOUD_PROJECT}
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - id: short_sha
        run: echo 'short_sha=$(git rev-parse --short HEAD)' >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          build-args: APPLICATION_NAME=${{ env.APPLICATION_NAME }}
          context: ${{ matrix.cache_scope }}/
          cache-from: type=gha,scope=${{ matrix.cache_scope }}
          cache-to:
            ${{ github.ref == 'refs/heads/main' &&
            format('type=gha,mode=max,scope={0}', matrix.scope) || '' }}
          file: ${{ matrix.cache_scope }}/Dockerfile
          push: ${{ github.ref == 'refs/head/main' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.GCLOUD_PROJECT }}/firezone/${{ matrix.image_name }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.GCLOUD_PROJECT }}/firezone/${{ matrix.image_name }}:${{ steps.short_sha.outputs.short_sha }}
          outputs: type=docker,dest=/tmp/${{ matrix.image_name }}.tar
      - name: Upload built images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: /tmp/${{ matrix.image_name }}.tar

  integration-tests:
    needs: build-containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test_name: Relayed flow
            setup: |
              #  Disallow traffic between gateway and client container
              sudo iptables -I FORWARD 1 -s  172.28.0.100 -d 172.28.0.105 -j DROP
              sudo iptables -I FORWARD 1 -s  172.28.0.105 -d 172.28.0.100 -j DROP
            execute: |
              docker compose exec -it client timeout 60 \
              bash -c 'until ping -W 1 -c 1 172.20.0.100 &>/dev/null; do true; done'
          - test_name: Basic flow
            setup: echo 'Noop'
            execute: |
              docker compose exec -it client timeout 60 \
              bash -c 'until ping -W 1 -c 1 172.20.0.100 &>/dev/null; do true; done'

    steps:
      - uses: actions/checkout@v4
      - name: Download built image artifacts
        uses: actions/download-artifact@v3
        with:
          name: images
          path: /tmp
      - name: Load images into docker
        run: |
          for image in /tmp/*.tar; do
            docker load --input $image
            docker tag $image firezone/$image
          done
          docker image ls -a
      - name: Seed database
        run:
          docker compose run elixir /bin/sh -c 'cd apps/domain && mix ecto.seed'
      - name: Start docker compose in the background
        run: docker compose up -d
      - name: Setup ${{ matrix.test_name }} test
        run: ${{ matrix.setup }}
      - name: Execute ${{ matrix.test_name }} test
        run: ${{ matrix.execute }}
      - name: Show Client logs
        if: "!cancelled()"
        run: docker compose logs client
      - name: Show Relay logs
        if: "!cancelled()"
        run: docker compose logs relay
      - name: Show Gateway logs
        if: "!cancelled()"
        run: docker compose logs gateway
      - name: Show API logs
        if: "!cancelled()"
        run: docker compose logs api
      - name: Show httpbin logs
        if: "!cancelled()"
        run: docker compose logs httpbin
