name: Publish image to Docker Hub

on:
  release:
    types: [published]

jobs:
  deploy-app:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/amd64/v2
          - linux/amd64/v3
          - linux/arm64
          # These build just fine, but is anyone using them?
          # - linux/arm/v7
          # - linux/arm/v6
          # - linux/ppc64le
          # - linux/s390x
          # These don't have Alpine images available
          # - linux/riscv64
          # - linux/386
          # - linux/mips64le
          # - linux/mips64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              platforms = ["${{ matrix.platform }}"]

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push App
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.prod
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/firezone:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
