name: End to end tests
on:
  # TODO
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  pull_request:


concurrency:
  group: "e2e-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup-e2e:
    defaults:
      working-directory: ./e2e
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo "Spin up docker test environment"

  macos:
    defaults:
      working-directory: ./e2e
    needs: setup-e2e
    runs-on: macos-14-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  windows:
    defaults:
      working-directory: ./e2e
    needs: setup-e2e
    runs-on: windows-11-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  linux:
    defaults:
      working-directory: ./e2e
    needs: setup-e2e
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  android:
    defaults:
      working-directory: ./e2e
    needs: setup-e2e
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  chromeos:
    defaults:
      working-directory: ./e2e
    needs: setup-e2e
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  ios:
    defaults:
      working-directory: ./e2e
    needs: setup-e2e
    runs-on: macos-14-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  ipados:
    defaults:
      working-directory: ./e2e
    needs: setup-e2e
    runs-on: macos-14-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  teardown-e2e:
    defaults:
      working-directory: ./e2e
    needs:
      - macos
      - windows
      - linux
      - android
      - chromeos
      - ios
      - ipados
    if: 'always()'
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Teardown e2e environment'
