name: End to end tests
on:
  # TODO
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: ./e2e

concurrency:
  group: "e2e-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup-e2e:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - macos-14-firezone
          - windows-11-firezone
          - ubuntu-22.04-firezone
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm i --location=global appium

  docker-up:
    needs: setup-e2e
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo "Spin up docker test environment"

  macos:
    needs: docker-up
    runs-on: macos-14-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  windows:
    needs: docker-up
    runs-on: windows-11-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  linux:
    needs: docker-up
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  android:
    needs: docker-up
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  chromeos:
    needs: docker-up
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  ios:
    needs: docker-up
    runs-on: macos-14-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  ipados:
    needs: docker-up
    runs-on: macos-14-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  teardown-e2e:
    needs:
      - macos
      - windows
      - linux
      - android
      - chromeos
      - ios
      - ipados
    if: 'always()'
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Teardown e2e environment'
