name: End to end tests
on:
  # TODO
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  pull_request:

concurrency:
  group: "e2e-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - macos-14-firezone
          - windows-11-firezone
          - ubuntu-22.04-firezone
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: './e2e/pnpm-lock.yaml'
      - run: pnpm i

  docker:
    needs: setup
    runs-on: ubuntu-22.04-firezone
    env:
      # mark:automatic-version
      VERSION: "1.0.0"
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d postgres
      - run: docker compose run elixir /bin/sh -c 'cd apps/domain && mix do ecto.create, ecto.migrate, ecto.seed'
      - name: Build images
        run: |
          docker compose build
      - name: Start docker compose in the background
        run: |
          docker compose up -d \
            api \
            web \
            client \
            relay \
            gateway \
            iperf3
      - name: Wait for client to ping resource
        run: |
          docker compose exec -it client timeout 60 \
          sh -c 'until ping -W 1 -c 1 172.20.0.100 &>/dev/null; do true; done'

  macos:
    needs: docker
    runs-on: macos-14-firezone
    permissions:
      contents: read
      id-token: 'write'
    defaults:
      run:
        working-directory: ./swift/apple
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          targets: aarch64-apple-darwin aarch64-apple-ios
      - name: build macos app
        run: |
          # Copy xcconfig
          cp Firezone/xcconfig/debug.xcconfig Firezone/xcconfig/config.xcconfig

          # Build app bundle
          xcodebuild build \
            -allowProvisioningUpdates \
            -configuration Debug \
            -scheme Firezone \
            -sdk macosx \
            -destination 'platform=macOS'

  windows:
    needs: docker
    runs-on: windows-11-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  linux:
    needs: docker
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  android:
    needs: docker
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Noop'

  ios:
    strategy:
      matrix:
        destination:
          - "Jamil's iPhone"
          - "Jamil's iPad"
    needs: docker
    runs-on: macos-14-firezone
    permissions:
      contents: read
      id-token: 'write'
    defaults:
      run:
        working-directory: ./swift/apple
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          targets: aarch64-apple-darwin aarch64-apple-ios
      - name: build ios app
        run: |
          # Copy xcconfig
          cp Firezone/xcconfig/debug.xcconfig Firezone/xcconfig/config.xcconfig

          # Build archive
          xcodebuild archive \
            -allowProvisioningUpdates \
            -archivePath $RUNNER_TEMP/Firezone.xcarchive \
            -configuration Debug \
            -scheme Firezone \
            -sdk iphoneos \
            -destination "platform=iOS,name=${{ matrix.destination }}"

  teardown:
    needs:
      - macos
      - windows
      - linux
      - android
      - ios
    if: 'always()'
    runs-on: ubuntu-22.04-firezone
    steps:
      - uses: actions/checkout@v4
      - run: docker compose logs postgres
      - run: docker compose logs vault
      - run: docker compose logs web
      - run: docker compose logs client
      - run: docker compose logs gateway
      - run: docker compose logs relay
      - run: docker compose logs elixir
      - run: docker compose logs api
      - run: |
          docker compose down -v

          # TODO: Granularly prune to preserve build cache
          # docker system prune --force --all --volumes
