name: Kotlin
on:
  workflow_call:

# Cancel old workflow runs if new code is pushed
concurrency:
  group: "kotlin-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # See rust.yml how we build, package and release connlib as an example
  build:
    runs-on: ubuntu-22.04-firezone
    defaults:
      run:
        working-directory: ./kotlin/android
    steps:
      - uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup show
        working-directory: ./rust
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          key: ${{ runner.os }}
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Create Local Properties File
        run: touch local.properties
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ./kotlin/android
      - name: Run linter
        run: ./gradlew spotlessCheck
      - name: Execute Gradle build
        run: ./gradlew assembleRelease
      - name: Run Test
        run: ./gradlew testReleaseUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: "!cancelled()"
