name: Kotlin
on:
  workflow_call:

# Cancel old workflow runs if new code is pushed
concurrency:
  group: "kotlin-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin/android
    steps:
      - uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup show
        working-directory: ./rust
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          key: ${{ runner.os }}-${{ github.ref }}
          # save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          cache-read-only: false # ${{ github.ref != 'refs/heads/main' }}
          build-root-directory: ./kotlin/android
      - run: touch local.properties
      - name: Run linter
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin/android
    steps:
      - uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup show
        working-directory: ./rust
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          key: ${{ runner.os }}-${{ github.ref }}
          # save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          cache-read-only: false
          build-root-directory: ./kotlin/android
          # https://github.com/gradle/gradle-build-action#overwriting-an-existing-gradle-user-home
          cache-overwrite-existing: true #${{ github.ref == 'refs/heads/main' }}
      - run: touch local.properties
      - name: Execute Gradle build
        run: ./gradlew assembleRelease
      - name: Run Test
        run: ./gradlew testReleaseUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: "!cancelled()"
