name: Kotlin
on:
  pull_request:
    paths:
      - "kotlin/**"
      - "rust/connlib/**"
      - ".github/workflows/kotlin.yml"
  merge_group:
    types: [checks_requested]
  workflow_call:
  workflow_dispatch:

# Cancel old workflow runs if new code is pushed
concurrency:
  group: "kotlin-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # See rust.yml how we build, package and release connlib as an example
  kotlin_build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin/android
    steps:
      - uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          shared-key: ${{ runner.os }}
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache/restore@v3
        name: Restore Gradle Cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create Local Properties File
        run: touch local.properties
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ./kotlin/android
      - name: Run linter
        run: ./gradlew spotlessCheck
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Run Test
        run: ./gradlew testReleaseUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: '!cancelled()'
      - uses: actions/cache/save@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Save Gradle Cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
