name: Kotlin
on:
  workflow_call:

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./kotlin/android
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          build-root-directory: ./kotlin/android
      - run: touch local.properties
      - name: Run linter
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kotlin/android
    steps:
      - uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup show
        working-directory: ./rust
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rust
          key: ubuntu-22.04-${{ runner.arch }}
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          build-root-directory: ./kotlin/android
          # https://github.com/gradle/gradle-build-action#overwriting-an-existing-gradle-user-home
          cache-overwrite-existing: ${{ github.ref == 'refs/heads/main' }}
      - name: Write secrets to paths
        env:
          KEYSTORE_BASE64: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{  secrets.GOOGLE_UPLOAD_KEYSTORE_KEY_PASSWORD }}
          FIREBASE_APP_DISTRIBUTION_CREDENTIALS: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}
          FIREBASE_APP_TESTERS: ${{ vars.FIREBASE_APP_TESTERS }}
        run: |
          # Gradle complains if it doesn't find this :-/
          touch local.properties

          # Write secrets to files for Gradle to find
          FIREBASE_APP_DISTRIBUTION_CREDENTIALS_PATH=$(pwd)/firebase-credentials.json
          KEYSTORE_PATH=$(pwd)/app/keystore.jks
          echo -n "$FIREBASE_APP_DISTRIBUTION_CREDENTIALS" > $FIREBASE_APP_DISTRIBUTION_CREDENTIALS_PATH
          echo -n "$KEYSTORE_BASE64" | base64 --decode > $KEYSTORE_PATH
      - name: Bundle and sign release
        run: ./gradlew bundleRelease
      # TODO: See https://github.com/firezone/firezone/issues/2311
      # TODO: See https://github.com/firezone/firezone/issues/2309
      - name: Run Test
        run: ./gradlew testReleaseUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: "!cancelled()"
      - name: Upload release
        # if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew appDistributionUploadRelease
