name: Deploy Production and Publish Images
run-name: Triggered by ${{ github.actor }}
on:
  release:
    types:
      - published

env:
  # mark:automatic-version
  VERSION: "1.0.4"

concurrency:
  group: "publish-production-${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  deploy-production:
    secrets: inherit
    uses: ./.github/workflows/_deploy_production.yml

  publish-images-to-ghcr:
    needs: deploy-production
    runs-on: ubuntu-22.04
    permissions:
      # Needed to upload artifacts to a release
      packages: write
      # Needed to login to GCP
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gcp-docker-login
        id: login
        with:
          project: firezone-prod
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Pull and push
        run: |
          set -xe

          IMAGES=(domain api web gateway relay client)
          MAJOR_VERSION="${VERSION%%.*}"
          MAJOR_MINOR_VERSION="${VERSION%.*}"

          for image in "${IMAGES[@]}"; do
            SOURCE_TAG=${{ steps.login.outputs.registry }}/firezone/${image}:${{ inputs.tag || github.sha }}

            docker buildx imagetools create \
              -t ghcr.io/firezone/${image}:${{ inputs.tag || github.sha }} \
              -t ghcr.io/firezone/${image}:${{ env.VERSION }} \
              -t ghcr.io/firezone/${image}:${{ env.VERSION }} \
              -t ghcr.io/firezone/${image}:${{ env.VERSION }}-${{ inputs.tag || github.sha }} \
              -t ghcr.io/firezone/${image}:latest \
              -t ghcr.io/firezone/${image}:${MAJOR_VERSION} \
              -t ghcr.io/firezone/${image}:${MAJOR_MINOR_VERSION} \
              $SOURCE_TAG
          done
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
          service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
          export_environment_variables: true
          create_credentials_file: true
      - name: Copy Google Cloud Storage binaries to "latest" version
        run: |
          set -xe

          IMAGES=(firezone-gateway)
          ARCHITECTURES=(x86_64 aarch64 armv7)
          MAJOR_VERSION="${VERSION%%.*}"
          MAJOR_MINOR_VERSION="${VERSION%.*}"

          for image in "${IMAGES[@]}"; do
            for arch in "${ARCHITECTURES[@]}"; do
              # Copy sha256sum.txt
              gcloud storage cp \
                gs://firezone-staging-artifacts/${image}/${{ env.VERSION }}-${{ inputs.sha }}/${arch}.sha256sum.txt \
                gs://firezone-prod-artifacts/${image}/latest/${arch}.sha256sum.txt

              gcloud storage cp \
                gs://firezone-staging-artifacts/${image}/${{ env.VERSION }}-${{ inputs.sha }}/${arch}.sha256sum.txt \
                gs://firezone-prod-artifacts/${image}/${{ env.VERSION }}/${arch}.sha256sum.txt

              # Copy binaries
              gcloud storage cp \
                gs://firezone-staging-artifacts/${image}/${{ env.VERSION }}-${{ inputs.sha }}/${arch} \
                gs://firezone-prod-artifacts/${image}/latest/${arch}

              gcloud storage cp \
                gs://firezone-staging-artifacts/${image}/${{ env.VERSION }}-${{ inputs.sha }}/${arch} \
                gs://firezone-prod-artifacts/${image}/${{ env.VERSION }}/${arch}
            done
          done
