name: Publish Images
run-name: Triggered by ${{ github.actor }}
on:
  release:
    types:
      - published
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy. Defaults to the last commit SHA in the branch."
        type: string
        default: ${{ github.sha }}
        required: false

concurrency:
  group: "publish-production-${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  publish-images-to-ghcr:
    runs-on: ubuntu-22.04
    permissions:
      # Needed to upload artifacts to a release
      packages: write
      # Needed to login to GCP
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gcp-docker-login
        id: login
        with:
          # Deploy from staging artifacts since it what was built on main
          project: firezone-staging
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Pull and push
        run: |
          set -xe


          if [[ "${{ github.event.release.name }}" =~ gateway* ]]; then
            image=gateway
            # mark:next-gateway-version
            VERSION="1.0.7"
          elif [[ "${{ github.event.release.name }}" =~ headless* ]]; then
            image=client
            # mark:next-headless-version
            VERSION="1.0.7"
          else
            echo "Release doesn't require publishing Docker images"
            exit 0
          fi

          MAJOR_VERSION="${VERSION%%.*}"
          MAJOR_MINOR_VERSION="${VERSION%.*}"

          SOURCE_TAG=${{ steps.login.outputs.registry }}/firezone/${image}:${{ inputs.tag || github.sha }}

          docker buildx imagetools create \
            -t ghcr.io/firezone/${image}:${{ inputs.tag || github.sha }} \
            -t ghcr.io/firezone/${image}:${VERSION} \
            -t ghcr.io/firezone/${image}:${VERSION} \
            -t ghcr.io/firezone/${image}:${VERSION}-${{ inputs.tag || github.sha }} \
            -t ghcr.io/firezone/${image}:latest \
            -t ghcr.io/firezone/${image}:${MAJOR_VERSION} \
            -t ghcr.io/firezone/${image}:${MAJOR_MINOR_VERSION} \
            $SOURCE_TAG
