name: Rust
on:
  workflow_call:

defaults:
  run:
    working-directory: ./rust

env:
  SCCACHE_GCS_BUCKET: "firezone-sccache"
  SCCACHE_GCS_RW_MODE: "READ_WRITE"
  RUSTC_WRAPPER: "sccache"

jobs:
  static-analysis:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          # We only need to run static analysis checks per OS family
          - ubuntu-22.04
          - macos-13
          - windows-2022
        # TODO: https://github.com/rust-lang/cargo/issues/5220
        include:
          - runs-on: ubuntu-22.04
            packages: # Intentionally blank as a package catch-all linter
          - runs-on: macos-13
            packages: -p connlib-client-apple
          - runs-on: windows-2022
            packages: -p connlib-client-shared
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
          service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy
      - run: cargo fmt -- --check
      - run: |
          cargo doc --all-features --no-deps --document-private-items ${{ matrix.packages }}
        env:
          RUSTDOCFLAGS: "-D warnings"
      - run: |
          cargo clippy --all-targets --all-features ${{ matrix.packages }} -- -D warnings
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO: https://github.com/rust-lang/cargo/issues/5220
        include:
          - runs-on: ubuntu-20.04
            packages: -p firezone-headless-client -p firezone-gateway -p connlib-client-android
          - runs-on: ubuntu-22.04
            packages: -p firezone-headless-client -p firezone-gateway -p connlib-client-android
          - runs-on: macos-12
            packages: -p connlib-client-apple
          - runs-on: macos-13
            packages: -p connlib-client-apple
          - runs-on: windows-2019
            packages: -p connlib-client-shared
          - runs-on: windows-2022
            packages: -p connlib-client-shared
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
          service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features ${{ matrix.packages }}
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

  smoke-test-relay:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./rust/relay
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
          service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: dtolnay/rust-toolchain@stable
      - run: ./run_smoke_test.sh
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
