name: Rust CI
on:
  pull_request:
    paths:
      - 'rust/**'
  push:
    branches:
      - master
    paths:
      - 'rust/**'

# Cancel old workflow runs if new code is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
