# Workaround for the problem described here:
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks
name: Terraform
on:
  merge_group:
    type: [checks_requested]
  pull_request:
    paths-ignore:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
  workflow_call:
  workflow_dispatch:

jobs:
  terraform_plan-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
