name: Update Dependencies
on: workflow_dispatch

jobs:
  install-packages:
    runs-on: ${{ matrix.platform }}
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      # Failing fast breaks the Omnibus build cache because the job is
      # interrupted abruptly, leaving behind index.lock files.
      fail-fast: false
      matrix:
        platform:
          # ARM-based
          - amazonlinux2-arm64
          - centos9-arm64
          - debian10-arm64
          - debian11-arm64
          - fedora33-arm64
          - fedora34-arm64
          - fedora35-arm64
          - ubuntu1804-arm64
          - ubuntu2004-arm64

          # x64-based
          - amazonlinux2-x64
          - centos7-x64
          - centos8-x64
          - centos9-x64
          - debian10-x64
          - debian11-x64
          - fedora33-x64
          - fedora34-x64
          - fedora35-x64
          - ubuntu1804-x64
          - ubuntu2004-x64
          - opensuse15-x64
    steps:
      - name: install llvm on suse-based
        if: startsWith(matrix.platform, 'opensuse')
        run: |
          sudo zypper refresh
          sudo zypper --non-interactive install llvm clang
      - name: install llvm on redhat-based
        if: >
          startsWith(matrix.platform, 'amazonlinux') ||
          startsWith(matrix.platform, 'centos') ||
          startsWith(matrix.platform, 'fedora') ||
          startsWith(matrix.platform, 'fedora')
        run: |
          sudo yum install -y llvm clang
      - name: install llvm on debian-based
        if: >
          startsWith(matrix.platform, 'debian') ||
          startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -yq llvm clang
